In [5]:
import torch
import torchvision
from torch import nn

In [37]:
y1 = torch.tensor([[0.5, 0.2, 0.05, 0.1, 0.05, 0.1],[0.5, 0.2, 0.05, 0.1, 0.05, 0.1]], requires_grad=True)
y2 = torch.tensor([[0.5, 0.2, 0.1, 0.05, 0.1, 0.05],[0.5, 0.2, 0.1, 0.05, 0.1, 0.05]], requires_grad=True)

In [31]:
class MSEEntropyLoss(nn.Module):
    def __init__(self):
        super(MSEEntropyLoss, self).__init__()
        self.MSE = nn.MSELoss()
    def forward(self, p_target: torch.Tensor, p_estimate: torch.Tensor):
        assert p_target.shape == p_estimate.shape
        entropy_target = torch.sum(-p_target.mul(p_target.log()), dim=1)
        entropy_estimate = torch.sum(-p_estimate.mul(p_estimate.log()), dim=1)
        entropy_diff = self.MSE(entropy_estimate, entropy_target)
        return entropy_diff.mean()
MSEEntropy = MSEEntropyLoss()

In [34]:
y1, y1.log(), y1*y1.log(),  torch.sum(y1*y1.log(), dim=1)

(tensor([[0.5000, 0.2000, 0.0500, 0.1000, 0.0500, 0.1000],
         [0.5000, 0.2000, 0.0500, 0.1000, 0.0500, 0.1000]]),
 tensor([[-0.6931, -1.6094, -2.9957, -2.3026, -2.9957, -2.3026],
         [-0.6931, -1.6094, -2.9957, -2.3026, -2.9957, -2.3026]]),
 tensor([[-0.3466, -0.3219, -0.1498, -0.2303, -0.1498, -0.2303],
         [-0.3466, -0.3219, -0.1498, -0.2303, -0.1498, -0.2303]]),
 tensor([-1.4286, -1.4286]))

In [38]:
loss = MSEEntropy(y1, y2)

In [39]:
loss.backward()

In [40]:
y1.grad , y2.grad

(tensor([[ 3.6580e-08, -7.2651e-08, -2.3791e-07, -1.5528e-07, -2.3791e-07,
          -1.5528e-07],
         [ 3.6580e-08, -7.2651e-08, -2.3791e-07, -1.5528e-07, -2.3791e-07,
          -1.5528e-07]]),
 tensor([[-3.6580e-08,  7.2651e-08,  1.5528e-07,  2.3791e-07,  1.5528e-07,
           2.3791e-07],
         [-3.6580e-08,  7.2651e-08,  1.5528e-07,  2.3791e-07,  1.5528e-07,
           2.3791e-07]]))

In [41]:
y1, y2

(tensor([[0.5000, 0.2000, 0.0500, 0.1000, 0.0500, 0.1000],
         [0.5000, 0.2000, 0.0500, 0.1000, 0.0500, 0.1000]], requires_grad=True),
 tensor([[0.5000, 0.2000, 0.1000, 0.0500, 0.1000, 0.0500],
         [0.5000, 0.2000, 0.1000, 0.0500, 0.1000, 0.0500]], requires_grad=True))